name: "🗃 Everything else"
description: Questions and issues that do not fit another category
title: ""
body:
  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-submission checklist
      options:
        - label: I searched existing issues and believe this is not a duplicate.
          required: true
        - label: I searched the [ActivityWatch documentation](https://docs.activitywatch.net/en/latest/) and did not find an answer.
          required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: |
        Describe the question or issue in detail.
        For help or support, please use the forum: https://forum.activitywatch.net/
    validations:
      required: true
