FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive
ARG USID=1000 GRID=1000

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates apt-transport-https adduser \
            build-essential zip unzip git curl \
            python3 python3-dev python3-pip python3-venv curl \
            pkgconf libssl-dev libxkbcommon-dev  libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd -g $GRID odoo && useradd --create-home -u $USID -g odoo -G audio,video odoo

RUN mkdir -p /data/build && chown -R odoo:odoo /data/build

USER odoo

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/home/odoo/.cargo/bin:${PATH}"

ENV NVM_DIR=/home/odoo/.nvm
ENV NODE_VERSION=22.22.1
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash && \
    bash -c "source $NVM_DIR/nvm.sh && \
             nvm install $NODE_VERSION && \
             nvm alias default $NODE_VERSION && \
             nvm use default"

ENV PATH="$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH"

RUN rustup toolchain install nightly && \
    rustup default nightly

RUN python3 -m venv /data/build/awvenv
ENV PATH="/data/build/awvenv/bin:$PATH"
ENV VIRTUAL_ENV=/data/build/awvenv
RUN python3 -m pip install poetry==1.8.2
