"""
Multi-tier classifier combining user rules, built-in heuristics, and AI models.
"""

import logging
import re
from typing import Any, Dict, List, Optional, Tuple

from .ai_client import AIClassifierClient, ClassificationResult
from .heuristics import get_builtin_classes

logger = logging.getLogger(__name__)


class CompiledRule:
    def __init__(self, name: List[str], regex_str: str, ignore_case: bool = True):
        self.name = name
        self.regex_str = regex_str
        self.ignore_case = ignore_case
        flags = (re.IGNORECASE if ignore_case else 0) | re.UNICODE
        try:
            self.pattern = re.compile(regex_str, flags)
        except re.error as exc:
            logger.warning(f"Failed to compile regex '{regex_str}' for category {name}: {exc}")
            self.pattern = None

    def matches(self, text: str) -> bool:
        if not self.pattern:
            return False
        return bool(self.pattern.search(text))


class MultiTierClassifier:
    def __init__(
        self,
        server_rules: Optional[List[Tuple[List[str], Dict[str, Any]]]] = None,
        ai_client: Optional[AIClassifierClient] = None,
        enable_heuristics: bool = True,
    ):
        self.ai_client = ai_client
        self.enable_heuristics = enable_heuristics
        self.server_rules: List[CompiledRule] = []
        self.heuristic_rules: List[CompiledRule] = []

        if server_rules:
            self.set_server_rules(server_rules)

        if enable_heuristics:
            self._load_heuristics()

    def set_server_rules(self, rules: List[Tuple[List[str], Dict[str, Any]]]) -> None:
        self.server_rules = []
        for name, spec in rules:
            regex_str = spec.get("regex", "")
            if regex_str:
                ignore_case = spec.get("ignore_case", True)
                self.server_rules.append(CompiledRule(name, regex_str, ignore_case))

    def _load_heuristics(self) -> None:
        self.heuristic_rules = []
        for name, spec in get_builtin_classes():
            regex_str = spec.get("regex", "")
            if regex_str:
                ignore_case = spec.get("ignore_case", True)
                self.heuristic_rules.append(CompiledRule(name, regex_str, ignore_case))

    def get_all_category_names(self) -> List[List[str]]:
        """Returns unique category paths across server rules and heuristics."""
        seen = set()
        categories = []
        for rule in self.server_rules + self.heuristic_rules:
            key = tuple(rule.name)
            if key not in seen:
                seen.add(key)
                categories.append(rule.name)
        return categories

    def classify(
        self,
        app: str,
        title: str,
        url: str = "",
        use_ai: bool = True,
    ) -> Tuple[List[str], float, str, Optional[str]]:
        """
        Classifies an activity.
        Returns tuple of:
          - category: List[str] (e.g. ["Work", "Programming"])
          - confidence: float (0.0 to 1.0)
          - source: str ("server_rule" | "heuristic" | "ai" | "uncategorized")
          - suggested_regex: Optional[str] (regex string if generated by AI)
        """
        search_text = f"{app} {title} {url}".strip()

        # 1. Check user/server-defined rules (highest priority)
        matched_server = [r.name for r in self.server_rules if r.matches(search_text)]
        if matched_server:
            # Deepest hierarchy wins
            best = max(matched_server, key=len)
            return best, 1.0, "server_rule", None

        # 2. Check built-in heuristics
        if self.enable_heuristics:
            matched_heuristics = [r.name for r in self.heuristic_rules if r.matches(search_text)]
            if matched_heuristics:
                best = max(matched_heuristics, key=len)
                return best, 0.95, "heuristic", None

        # 3. AI classification
        if use_ai and self.ai_client and self.ai_client.is_configured():
            ai_res = self.ai_client.classify_single(
                app=app,
                title=title,
                url=url,
                existing_categories=self.get_all_category_names(),
            )
            if ai_res and ai_res.category and ai_res.category != ["Uncategorized"]:
                return ai_res.category, ai_res.confidence, "ai", ai_res.regex

        # 4. Fallback
        return ["Uncategorized"], 0.0, "uncategorized", None
