name: Diagram

on:
  workflow_dispatch: {}
  push:
    branches:
      - diagram
     #- master  # protected branch, can't push updated diagram to

jobs:
  update-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Also checkout docs & website
        run: |
          git clone https://github.com/ActivityWatch/docs
          git clone https://github.com/ActivityWatch/activitywatch.github.io
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          commit_message: 'chore: update diagram [skip ci]'
          file_colors: '{"rs": "#b7410e", "py": "#229922", "rst": "pink", "txt": "pink", "md": "pink", "css": "purple", "scss": "purple"}'
          excluded_globs: "**/.github;**/.git;**/*.builds;**/*.bat;**/*.iss;**/*.ps1;**/*.pyi;**/*.plist;**/*.cmd"
          #excluded_paths: '.github'
